### PR TITLE
Dedupe Project Contact Getlist; Log Own Hours Menu Item;

### PR DESCRIPTION
**Pull request by ginkgomzd**

### CODE REVIEW

**Comment by colemanw** [comment]
@GinkgoFJG @ginkgomzd this isn't quite how gitlist is supposed to work. The reason it typically sets a limit of 10 is because of its "infinite scroll" capability. (you can see this in action with most select2-based EntityRef fields - scroll down the list and it will fetch the next 10 results and so on.
If you are fetching 100 results then whittling the list down in php... that's not going to work so great.
Maybe a sql DISTINCT or GROUP BY could solve this?

**Comment by ginkgomzd** [comment]
@colemanw  I think this is a special case because of the many-to-many nature of the entity.
I went digging for some time trying to understand how we could alter the SQL in the DAO and came up short. It would have to be a group-by. Note also that we discard the entity id.

Maybe infinite scroll is the answer to our problem, in which case, I'd love to have 6 hours of my life back. Problem was I was only getting a very small number of auto-complete suggestions after de-duping. Is there a config for autoscroll, or is the user expected to arrow-down to the last item in the list? I think I would never find that feature because that's not how autocomplete suggestions work. The enticement is to keep typing, not scroll-down for more.

I made sure that a user could specify a limit in the

**Comment by colemanw** [comment]
EntityRef fields and the getlist api work together to automatically do 
infinite scrolling, you should't have to do anything for it to work.

**Comment by ginkgomzd** [comment]
I will always agree that I shouldn't have to do anything.
However... do you see my point, that users don't scroll in auto-complete?

**Comment by colemanw** [comment]
No, 'getlist' is only ever used by select2 autocompletes.

Maybe I don't understand your use-case, but if your users are wanting to 
scroll through the list of results, and the widget automatically gives 
you infinite scrolling... what's the problem?

**Comment by ginkgomzd** [comment]
I think there is no clear "best" behavior here. I confirmed for myself that infinite-scroll indeed requires scrolling to the bottom of the list. Our instance starts with no results and asks the user to enter a search. We have a lot of duplicates because contacts have a lot of projects, of which they have multiple entries in this entity table for each project. So, dupes easily push out all other results. With the custom dedupe logic, my user testing often had 3 or 4 results displayed. There is no enticement to trigger the infinite scroll in this case.

I think if I spent a little more time on it, I could support the infinite scroll by creating a custom configuration so that the dedupe would not be the default. However, since duplicates are pretty much guaranteed with this data model, I think the behaviour implemented in this PR is fine for most cases.

I will create an issue to revisit this sometime in the future.

**Comment by ginkgomzd** [comment]
https://issues.civicrm.org/jira/browse/VOL-280

**Pull request merged**
